steps:
  shellcheck:
    image: koalaman/shellcheck:stable
    commands:
      - find . -name "*.sh" -exec shellcheck -s sh -S warning -e SC2154 {} +
  gitleaks:
    image: zricethezav/gitleaks:latest
    commands:
      - gitleaks detect --source . --verbose
